#ifndef CLAUDE_DESKTOP_PROFILES_MANAGER_VERSION_H
#define CLAUDE_DESKTOP_PROFILES_MANAGER_VERSION_H

#define APP_VERSION_MAJOR 1
#define APP_VERSION_MINOR 0
#define APP_VERSION_PATCH 1
#define APP_VERSION_STR   "1.0.1"
#define APP_VERSION_WSTR  L"1.0.1"

#endif
